name: PHPCS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show PHP & Composer
        run: |
          php -v || true
          composer --version || true

      - name: Install Composer (if missing)
        run: |
          if ! command -v composer >/dev/null 2>&1; then
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          fi
          composer --version

      - name: Install PHPCS tooling (global)
        run: |
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require --no-interaction --prefer-dist \
            squizlabs/php_codesniffer:^3.10 \
            wp-coding-standards/wpcs:^3.0 \
            phpcompatibility/php-compatibility:^9.3 \
            phpcompatibility/phpcompatibility-wp:^2.1

      - name: Configure PHPCS installed_paths (global)
        run: |
          GROOT="$HOME/.composer/vendor"
          ~/.composer/vendor/bin/phpcs --config-set installed_paths "$GROOT/wp-coding-standards/wpcs,$GROOT/phpcompatibility/php-compatibility,$GROOT/phpcompatibility/phpcompatibility-wp"
          ~/.composer/vendor/bin/phpcs -i
          ~/.composer/vendor/bin/phpcs --config-show

      - name: Run PHPCS
        run: ~/.composer/vendor/bin/phpcs --standard="$(pwd)/phpcs.xml.dist" -s
