name: PHPCS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Cache Composer (global)
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-${{ runner.os }}-

      # Install PHPCS + standards globally to avoid local vendor path issues
      - name: Install PHPCS tooling (global)
        run: |
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require --no-interaction --prefer-dist \
            squizlabs/php_codesniffer:^3.10 \
            wp-coding-standards/wpcs:^3.0 \
            phpcompatibility/php-compatibility:^9.3 \
            phpcompatibility/phpcompatibility-wp:^2.1

      - name: Show PHPCS version
        run: ~/.composer/vendor/bin/phpcs --version

      - name: Configure PHPCS installed_paths (global)
        run: |
          GROOT="$HOME/.composer/vendor"
          ~/.composer/vendor/bin/phpcs --config-set installed_paths \
            "$GROOT/wp-coding-standards/wpcs,$GROOT/phpcompatibility/php-compatibility,$GROOT/phpcompatibility/phpcompatibility-wp"
          ~/.composer/vendor/bin/phpcs -i
          ~/.composer/vendor/bin/phpcs --config-show

      # Run in the repo root using your phpcs.xml.dist
      - name: Run PHPCS
        run: ~/.composer/vendor/bin/phpcs --standard=phpcs.xml.dist
